### ISSUE TITLE
Build on docker does not work

### ISSUE THREAD

**Issue by Tofdu31** [IndoorLocation/meraki-indoor-location#15]
Hi all,

The build does not work.
Here's what i got when i run the command 
`docker build -t meraki-indoor-location:latest -f docker/Dockerfile .`

```
Sending build context to Docker daemon    148kB
Step 1/7 : FROM node:6-alpine
6-alpine: Pulling from library/node
d6a5679aa3cf: Pull complete 
3cc45d588a77: Pull complete 
d670f4c5d65c: Pull complete 
Digest: sha256:e9f69716044840be97aca80dae7dee0efd126e8043623478de9ab9bc19badccd
Status: Downloaded newer image for node:6-alpine
 ---> ac75c1f95b80
Step 2/7 : LABEL maintainer="Mapwize <support@mapwize.io>"
 ---> Running in bb0214519513
Removing intermediate container bb0214519513
 ---> e06cb682dd85
Step 3/7 : ENV INSTALL_PACKAGES git build-base
 ---> Running in 877f8606ed54
Removing intermediate container 877f8606ed54
 ---> 03bb21c81101
Step 4/7 : COPY . /root/meraki-indoor-location/
 ---> f0ccf7490b7a
Step 5/7 : WORKDIR /root/meraki-indoor-location
 ---> Running in 94a0012b4e72
Removing intermediate container 94a0012b4e72
 ---> 0a77e3f23443
Step 6/7 : RUN     apk --no-cache add $INSTALL_PACKAGES $RUNTIME_PACKAGES &&     npm config set user 0 &&     npm config set unsafe-perm true &&     git init && git clean -fdX && npm install --production &&     apk del $INSTALL_PACKAGES
 ---> Running in faf2002fd16d
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/23) Installing binutils-libs (2.26-r1)
(2/23) Installing binutils (2.26-r1)
(3/23) Installing gmp (6.1.0-r0)
(4/23) Installing isl (0.14.1-r0)
(5/23) Installing libgomp (5.3.0-r0)
(6/23) Installing libatomic (5.3.0-r0)
(7/23) Installing pkgconf (0.9.12-r0)
(8/23) Installing pkgconfig (0.25-r1)
(9/23) Installing mpfr3 (3.1.2-r0)
(10/23) Installing mpc1 (1.0.3-r0)
(11/23) Installing gcc (5.3.0-r0)
(12/23) Installing make (4.1-r1)
(13/23) Installing musl-dev (1.1.14-r16)
(14/23) Installing libc-dev (0.7-r0)
(15/23) Installing fortify-headers (0.8-r0)
(16/23) Installing g++ (5.3.0-r0)
(17/23) Installing build-base (0.4-r1)
(18/23) Installing ca-certificates (20161130-r0)
(19/23) Installing libssh2 (1.7.0-r0)
(20/23) Installing libcurl (7.60.0-r1)
(21/23) Installing expat (2.2.0-r1)
(22/23) Installing pcre (8.38-r1)
(23/23) Installing git (2.8.6-r0)
Executing busybox-1.24.2-r14.trigger
Executing ca-certificates-20161130-r0.trigger
OK: 174 MiB in 36 packages
Initialized empty Git repository in /root/meraki-indoor-location/.git/
npm WARN deprecated sphericalmercator@1.0.5: This module is now under the @mapbox namespace: install @mapbox/sphericalmercator instead
npm WARN deprecated uws@9.14.0: stop using this version

> node-expat@2.3.17 install /root/meraki-indoor-location/node_modules/node-expat
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:449:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:353:11
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:69:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 4.9.0-7-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/meraki-indoor-location/node_modules/node-expat
gyp ERR! node -v v6.14.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
meraki-indoor-location@2.0.0 /root/meraki-indoor-location
+-- async@2.6.0 
+-- body-parser@1.18.2 
| +-- bytes@3.0.0 
| +-- content-type@1.0.4 
| +-- debug@2.6.9 
| | `-- ms@2.0.0 
| +-- depd@1.1.2 
| +-- http-errors@1.6.3 
| | +-- inherits@2.0.3 
| | `-- statuses@1.5.0 
| +-- iconv-lite@0.4.19 
| +-- on-finished@2.3.0 
| | `-- ee-first@1.1.1 
| +-- qs@6.5.1 
| +-- raw-body@2.3.2 
| | +-- http-errors@1.6.2 
| | | +-- depd@1.1.1 
| | | `-- setprototypeof@1.0.3 
| | `-- unpipe@1.0.0 
| `-- type-is@1.6.16 
|   `-- media-typer@0.3.0 
+-- chalk@2.4.1 
| +-- ansi-styles@3.2.1 
| | `-- color-convert@1.9.3 
| |   `-- color-name@1.1.3 
| +-- escape-string-regexp@1.0.5 
| `-- supports-color@5.5.0 
|   `-- has-flag@3.0.0 
+-- commander@2.15.1 
+-- documentdb@1.14.2 
| +-- big-integer@1.6.36 
| +-- binary-search-bounds@2.0.3 
| +-- int64-buffer@0.1.10 
| +-- priorityqueuejs@1.0.0 
| +-- semaphore@1.0.5 
| +-- tunnel@0.0.5 
| `-- underscore@1.8.3 
+-- express@4.16.3 
| +-- accepts@1.3.5 
| | `-- negotiator@0.6.1 
| +-- array-flatten@1.1.1 
| +-- content-disposition@0.5.2 
| +-- cookie@0.3.1 
| +-- cookie-signature@1.0.6 
| +-- encodeurl@1.0.2 
| +-- escape-html@1.0.3 
| +-- etag@1.8.1 
| +-- finalhandler@1.1.1 
| | `-- statuses@1.4.0 
| +-- fresh@0.5.2 
| +-- merge-descriptors@1.0.1 
| +-- methods@1.1.2 
| +-- parseurl@1.3.2 
| +-- path-to-regexp@0.1.7 
| +-- proxy-addr@2.0.4 
| | +-- forwarded@0.1.2 
| | `-- ipaddr.js@1.8.0 
| +-- range-parser@1.2.0 
| +-- safe-buffer@5.1.1 
| +-- send@0.16.2 
| | +-- destroy@1.0.4 
| | +-- mime@1.4.1 
| | `-- statuses@1.4.0 
| +-- serve-static@1.13.2 
| +-- setprototypeof@1.1.0 
| +-- statuses@1.4.0 
| +-- utils-merge@1.0.1 
| `-- vary@1.1.2 
+-- flat@4.0.0 
| `-- is-buffer@1.1.6 
+-- image-size@0.6.2 
+-- ioredis@3.2.2 
| +-- bluebird@3.5.2 
| +-- cluster-key-slot@1.0.12 
| +-- denque@1.3.0 
| +-- flexbuffer@0.0.6 
| +-- lodash.assign@4.2.0 
| +-- lodash.bind@4.2.1 
| +-- lodash.clone@4.5.0 
| +-- lodash.clonedeep@4.5.0 
| +-- lodash.defaults@4.2.0 
| +-- lodash.difference@4.5.0 
| +-- lodash.flatten@4.4.0 
| +-- lodash.foreach@4.5.0 
| +-- lodash.isempty@4.4.0 
| +-- lodash.keys@4.2.0 
| +-- lodash.noop@3.0.1 
| +-- lodash.partial@4.2.1 
| +-- lodash.pick@4.4.0 
| +-- lodash.sample@4.2.1 
| +-- lodash.shuffle@4.2.0 
| +-- lodash.values@4.3.0 
| +-- redis-commands@1.3.5 
| `-- redis-parser@2.6.0 
+-- lodash@4.17.10 
+-- mapwize-node-api@0.2.0 
+-- mysql@2.16.0 
| +-- bignumber.js@4.1.0 
| +-- readable-stream@2.3.6 
| | +-- core-util-is@1.0.2 
| | +-- isarray@1.0.0 
| | +-- process-nextick-args@2.0.0 
| | +-- string_decoder@1.1.1 
| | `-- util-deprecate@1.0.2 
| +-- safe-buffer@5.1.2 
| `-- sqlstring@2.3.1 
+-- node-cache@4.2.0 
| `-- clone@2.1.2 
+-- request@2.85.0 
| +-- aws-sign2@0.7.0 
| +-- aws4@1.8.0 
| +-- caseless@0.12.0 
| +-- combined-stream@1.0.6 
| | `-- delayed-stream@1.0.0 
| +-- extend@3.0.2 
| +-- forever-agent@0.6.1 
| +-- form-data@2.3.2 
| | `-- asynckit@0.4.0 
| +-- har-validator@5.0.3 
| | +-- ajv@5.5.2 
| | | +-- co@4.6.0 
| | | +-- fast-deep-equal@1.1.0 
| | | +-- fast-json-stable-stringify@2.0.0 
| | | `-- json-schema-traverse@0.3.1 
| | `-- har-schema@2.0.0 
| +-- hawk@6.0.2 
| | +-- boom@4.3.1 
| | +-- cryptiles@3.1.2 
| | | `-- boom@5.2.0 
| | +-- hoek@4.2.1 
| | `-- sntp@2.1.0 
| +-- http-signature@1.2.0 
| | +-- assert-plus@1.0.0 
| | +-- jsprim@1.4.1 
| | | +-- extsprintf@1.3.0 
| | | +-- json-schema@0.2.3 
| | | `-- verror@1.10.0 
| | `-- sshpk@1.14.2 
| |   +-- asn1@0.2.4 
| |   +-- bcrypt-pbkdf@1.0.2 
| |   +-- dashdash@1.14.1 
| |   +-- ecc-jsbn@0.1.2 
| |   +-- getpass@0.1.7 
| |   +-- jsbn@0.1.1 
| |   +-- safer-buffer@2.1.2 
| |   `-- tweetnacl@0.14.5 
| +-- is-typedarray@1.0.0 
| +-- isstream@0.1.2 
| +-- json-stringify-safe@5.0.1 
| +-- mime-types@2.1.20 
| | `-- mime-db@1.36.0 
| +-- oauth-sign@0.8.2 
| +-- performance-now@2.1.0 
| +-- stringstream@0.0.6 
| +-- tough-cookie@2.3.4 
| | `-- punycode@1.4.1 
| +-- tunnel-agent@0.6.0 
| `-- uuid@3.3.2 
+-- socket.io@2.0.3 
| +-- engine.io@3.1.5 
| | +-- base64id@1.0.0 
| | +-- debug@3.1.0 
| | +-- engine.io-parser@2.1.2 
| | | +-- after@0.8.2 
| | | +-- arraybuffer.slice@0.0.7 
| | | `-- blob@0.0.4 
| | +-- uws@9.14.0 
| | `-- ws@3.3.3 
| |   +-- async-limiter@1.0.0 
| |   `-- ultron@1.1.1 
| +-- object-assign@4.1.1 
| +-- socket.io-adapter@1.1.1 
| +-- socket.io-client@2.0.4 
| | +-- backo2@1.0.2 
| | +-- base64-arraybuffer@0.1.5 
| | +-- component-bind@1.0.0 
| | +-- component-emitter@1.2.1 
| | +-- engine.io-client@3.1.6 
| | | +-- component-inherit@0.0.3 
| | | +-- debug@3.1.0 
| | | +-- xmlhttprequest-ssl@1.5.5 
| | | `-- yeast@0.1.2 
| | +-- has-cors@1.1.0 
| | +-- indexof@0.0.1 
| | +-- object-component@0.0.3 
| | +-- parseqs@0.0.5 
| | | `-- better-assert@1.0.2 
| | |   `-- callsite@1.0.0 
| | +-- parseuri@0.0.5 
| | `-- to-array@0.1.4 
| `-- socket.io-parser@3.1.3 
|   +-- debug@3.1.0 
|   +-- has-binary2@1.0.3 
|   | `-- isarray@2.0.1 
|   `-- isarray@2.0.1 
+-- sphericalmercator@1.0.5 
`-- utf8@3.0.0 

### npm ERR! Linux 4.9.0-7-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.3.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.17 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-expat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/meraki-indoor-location/npm-debug.log
The command '/bin/sh -c apk --no-cache add $INSTALL_PACKAGES $RUNTIME_PACKAGES &&     npm config set user 0 &&     npm config set unsafe-perm true &&     git init && git clean -fdX && npm install --production &&     apk del $INSTALL_PACKAGES' returned a non-zero code: 1
```

**Comment by mathieugerard** [comment]
Hi. Thanks for reaching out. We are investigating.

**Comment by mcolmant** [comment]
Hi, a fix has been pushed. Please could you retry?
Thanks,

**Comment by Tofdu31** [comment]
Hi,
Thank you for your responsiveness !!!

Here are the logs, I have 2 Warm

`Sending build context to Docker daemon    148kB
Step 1/7 : FROM node:6.14.4-alpine
6.14.4-alpine: Pulling from library/node
d6a5679aa3cf: Pull complete 
3cc45d588a77: Pull complete 
d670f4c5d65c: Pull complete 
Digest: sha256:e9f69716044840be97aca80dae7dee0efd126e8043623478de9ab9bc19badccd
Status: Downloaded newer image for node:6.14.4-alpine
 ---> ac75c1f95b80
Step 2/7 : LABEL maintainer="Mapwize <support@mapwize.io>"
 ---> Running in a92909e92854
Removing intermediate container a92909e92854
 ---> ba338e61a4b8
Step 3/7 : ENV INSTALL_PACKAGES git build-base python
 ---> Running in 192fe9deaea6
Removing intermediate container 192fe9deaea6
 ---> b1b547029df3
Step 4/7 : COPY . /root/meraki-indoor-location/
 ---> 0495ea634615
Step 5/7 : WORKDIR /root/meraki-indoor-location
 ---> Running in bfed61629a97
Removing intermediate container bfed61629a97
 ---> 7de4f74aeb1f
Step 6/7 : RUN     apk --no-cache add $INSTALL_PACKAGES $RUNTIME_PACKAGES &&     npm config set user 0 &&     npm config set unsafe-perm true &&     git init && git clean -fdX && npm install --production &&     apk del $INSTALL_PACKAGES
 ---> Running in b7e7ba6a1f5e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/32) Installing binutils-libs (2.26-r1)
(2/32) Installing binutils (2.26-r1)
(3/32) Installing gmp (6.1.0-r0)
(4/32) Installing isl (0.14.1-r0)
(5/32) Installing libgomp (5.3.0-r0)
(6/32) Installing libatomic (5.3.0-r0)
(7/32) Installing pkgconf (0.9.12-r0)
(8/32) Installing pkgconfig (0.25-r1)
(9/32) Installing mpfr3 (3.1.2-r0)
(10/32) Installing mpc1 (1.0.3-r0)
(11/32) Installing gcc (5.3.0-r0)
(12/32) Installing make (4.1-r1)
(13/32) Installing musl-dev (1.1.14-r16)
(14/32) Installing libc-dev (0.7-r0)
(15/32) Installing fortify-headers (0.8-r0)
(16/32) Installing g++ (5.3.0-r0)
(17/32) Installing build-base (0.4-r1)
(18/32) Installing ca-certificates (20161130-r0)
(19/32) Installing libssh2 (1.7.0-r0)
(20/32) Installing libcurl (7.60.0-r1)
(21/32) Installing expat (2.2.0-r1)
(22/32) Installing pcre (8.38-r1)
(23/32) Installing git (2.8.6-r0)
(24/32) Installing libbz2 (1.0.6-r5)
(25/32) Installing libffi (3.2.1-r2)
(26/32) Installing gdbm (1.11-r1)
(27/32) Installing ncurses-terminfo-base (6.0_p20171125-r0)
(28/32) Installing ncurses-terminfo (6.0_p20171125-r0)
(29/32) Installing ncurses-libs (6.0_p20171125-r0)
(30/32) Installing readline (6.3.008-r4)
(31/32) Installing sqlite-libs (3.13.0-r2)
(32/32) Installing python (2.7.14-r0)
Executing busybox-1.24.2-r14.trigger
Executing ca-certificates-20161130-r0.trigger
OK: 221 MiB in 45 packages
Initialized empty Git repository in /root/meraki-indoor-location/.git/
npm WARN deprecated sphericalmercator@1.0.5: This module is now under the @mapbox namespace: install @mapbox/sphericalmercator instead
npm WARN deprecated uws@9.14.0: stop using this version

> node-expat@2.3.17 install /root/meraki-indoor-location/node_modules/node-expat
> node-gyp rebuild

make: Entering directory '/root/meraki-indoor-location/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
../deps/libexpat/lib/xmlparse.c: In function 'gather_time_entropy':
../deps/libexpat/lib/xmlparse.c:780:7: warning: variable 'gettimeofday_res' set but not used [-Wunused-but-set-variable]
   int gettimeofday_res;
       ^
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/obj.target/node_expat.node
  COPY Release/node_expat.node
make: Leaving directory '/root/meraki-indoor-location/node_modules/node-expat/build'

> uws@9.14.0 install /root/meraki-indoor-location/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

meraki-indoor-location@2.0.0 /root/meraki-indoor-location
+-- async@2.6.0 
+-- body-parser@1.18.2 
| +-- bytes@3.0.0 
| +-- content-type@1.0.4 
| +-- debug@2.6.9 
| | `-- ms@2.0.0 
| +-- depd@1.1.2 
| +-- http-errors@1.6.3 
| | +-- inherits@2.0.3 
| | `-- statuses@1.5.0 
| +-- iconv-lite@0.4.19 
| +-- on-finished@2.3.0 
| | `-- ee-first@1.1.1 
| +-- qs@6.5.1 
| +-- raw-body@2.3.2 
| | +-- http-errors@1.6.2 
| | | +-- depd@1.1.1 
| | | `-- setprototypeof@1.0.3 
| | `-- unpipe@1.0.0 
| `-- type-is@1.6.16 
|   `-- media-typer@0.3.0 
+-- chalk@2.4.1 
| +-- ansi-styles@3.2.1 
| | `-- color-convert@1.9.3 
| |   `-- color-name@1.1.3 
| +-- escape-string-regexp@1.0.5 
| `-- supports-color@5.5.0 
|   `-- has-flag@3.0.0 
+-- commander@2.15.1 
+-- documentdb@1.14.2 
| +-- big-integer@1.6.36 
| +-- binary-search-bounds@2.0.3 
| +-- int64-buffer@0.1.10 
| +-- priorityqueuejs@1.0.0 
| +-- semaphore@1.0.5 
| +-- tunnel@0.0.5 
| `-- underscore@1.8.3 
+-- express@4.16.3 
| +-- accepts@1.3.5 
| | `-- negotiator@0.6.1 
| +-- array-flatten@1.1.1 
| +-- content-disposition@0.5.2 
| +-- cookie@0.3.1 
| +-- cookie-signature@1.0.6 
| +-- encodeurl@1.0.2 
| +-- escape-html@1.0.3 
| +-- etag@1.8.1 
| +-- finalhandler@1.1.1 
| | `-- statuses@1.4.0 
| +-- fresh@0.5.2 
| +-- merge-descriptors@1.0.1 
| +-- methods@1.1.2 
| +-- parseurl@1.3.2 
| +-- path-to-regexp@0.1.7 
| +-- proxy-addr@2.0.4 
| | +-- forwarded@0.1.2 
| | `-- ipaddr.js@1.8.0 
| +-- range-parser@1.2.0 
| +-- safe-buffer@5.1.1 
| +-- send@0.16.2 
| | +-- destroy@1.0.4 
| | +-- mime@1.4.1 
| | `-- statuses@1.4.0 
| +-- serve-static@1.13.2 
| +-- setprototypeof@1.1.0 
| +-- statuses@1.4.0 
| +-- utils-merge@1.0.1 
| `-- vary@1.1.2 
+-- flat@4.0.0 
| `-- is-buffer@1.1.6 
+-- image-size@0.6.2 
+-- ioredis@3.2.2 
| +-- bluebird@3.5.2 
| +-- cluster-key-slot@1.0.12 
| +-- denque@1.3.0 
| +-- flexbuffer@0.0.6 
| +-- lodash.assign@4.2.0 
| +-- lodash.bind@4.2.1 
| +-- lodash.clone@4.5.0 
| +-- lodash.clonedeep@4.5.0 
| +-- lodash.defaults@4.2.0 
| +-- lodash.difference@4.5.0 
| +-- lodash.flatten@4.4.0 
| +-- lodash.foreach@4.5.0 
| +-- lodash.isempty@4.4.0 
| +-- lodash.keys@4.2.0 
| +-- lodash.noop@3.0.1 
| +-- lodash.partial@4.2.1 
| +-- lodash.pick@4.4.0 
| +-- lodash.sample@4.2.1 
| +-- lodash.shuffle@4.2.0 
| +-- lodash.values@4.3.0 
| +-- redis-commands@1.3.5 
| `-- redis-parser@2.6.0 
+-- lodash@4.17.10 
+-- mapwize-node-api@0.2.0 
+-- mysql@2.16.0 
| +-- bignumber.js@4.1.0 
| +-- readable-stream@2.3.6 
| | +-- core-util-is@1.0.2 
| | +-- isarray@1.0.0 
| | +-- process-nextick-args@2.0.0 
| | +-- string_decoder@1.1.1 
| | `-- util-deprecate@1.0.2 
| +-- safe-buffer@5.1.2 
| `-- sqlstring@2.3.1 
+-- node-cache@4.2.0 
| `-- clone@2.1.2 
+-- request@2.85.0 
| +-- aws-sign2@0.7.0 
| +-- aws4@1.8.0 
| +-- caseless@0.12.0 
| +-- combined-stream@1.0.7 
| | `-- delayed-stream@1.0.0 
| +-- extend@3.0.2 
| +-- forever-agent@0.6.1 
| +-- form-data@2.3.2 
| | +-- asynckit@0.4.0 
| | `-- combined-stream@1.0.6 
| +-- har-validator@5.0.3 
| | +-- ajv@5.5.2 
| | | +-- co@4.6.0 
| | | +-- fast-deep-equal@1.1.0 
| | | +-- fast-json-stable-stringify@2.0.0 
| | | `-- json-schema-traverse@0.3.1 
| | `-- har-schema@2.0.0 
| +-- hawk@6.0.2 
| | +-- boom@4.3.1 
| | +-- cryptiles@3.1.2 
| | | `-- boom@5.2.0 
| | `-- sntp@2.1.0 
| +-- http-signature@1.2.0 
| | +-- assert-plus@1.0.0 
| | +-- jsprim@1.4.1 
| | | +-- extsprintf@1.3.0 
| | | +-- json-schema@0.2.3 
| | | `-- verror@1.10.0 
| | `-- sshpk@1.14.2 
| |   +-- asn1@0.2.4 
| |   +-- bcrypt-pbkdf@1.0.2 
| |   +-- dashdash@1.14.1 
| |   +-- ecc-jsbn@0.1.2 
| |   +-- getpass@0.1.7 
| |   +-- jsbn@0.1.1 
| |   +-- safer-buffer@2.1.2 
| |   `-- tweetnacl@0.14.5 
| +-- is-typedarray@1.0.0 
| +-- isstream@0.1.2 
| +-- json-stringify-safe@5.0.1 
| +-- mime-types@2.1.20 
| | `-- mime-db@1.36.0 
| +-- oauth-sign@0.8.2 
| +-- performance-now@2.1.0 
| +-- stringstream@0.0.6 
| +-- tough-cookie@2.3.4 
| | `-- punycode@1.4.1 
| +-- tunnel-agent@0.6.0 
| `-- uuid@3.3.2 
+-- socket.io@2.0.3 
| +-- engine.io@3.1.5 
| | +-- base64id@1.0.0 
| | +-- debug@3.1.0 
| | +-- engine.io-parser@2.1.2 
| | | +-- after@0.8.2 
| | | +-- arraybuffer.slice@0.0.7 
| | | `-- blob@0.0.4 
| | +-- uws@9.14.0 
| | `-- ws@3.3.3 
| |   +-- async-limiter@1.0.0 
| |   `-- ultron@1.1.1 
| +-- object-assign@4.1.1 
| +-- socket.io-adapter@1.1.1 
| +-- socket.io-client@2.0.4 
| | +-- backo2@1.0.2 
| | +-- base64-arraybuffer@0.1.5 
| | +-- component-bind@1.0.0 
| | +-- component-emitter@1.2.1 
| | +-- engine.io-client@3.1.6 
| | | +-- component-inherit@0.0.3 
| | | +-- debug@3.1.0 
| | | +-- xmlhttprequest-ssl@1.5.5 
| | | `-- yeast@0.1.2 
| | +-- has-cors@1.1.0 
| | +-- indexof@0.0.1 
| | +-- object-component@0.0.3 
| | +-- parseqs@0.0.5 
| | | `-- better-assert@1.0.2 
| | |   `-- callsite@1.0.0 
| | +-- parseuri@0.0.5 
| | `-- to-array@0.1.4 
| `-- socket.io-parser@3.1.3 
|   +-- debug@3.1.0 
|   +-- has-binary2@1.0.3 
|   | `-- isarray@2.0.1 
|   `-- isarray@2.0.1 
+-- sphericalmercator@1.0.5 
+-- utf8@3.0.0 
`-- xml2json@0.11.2 
  +-- hoek@4.2.1 
  +-- joi@13.6.0 
  | +-- hoek@5.0.4 
  | +-- isemail@3.1.3 
  | | `-- punycode@2.1.1 
  | `-- topo@3.0.0 
  |   `-- hoek@5.0.4 
  `-- node-expat@2.3.17 
    +-- bindings@1.3.0 
    `-- nan@2.11.0 

WARNING: Ignoring APKINDEX.167438ca.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.a2e6dac0.tar.gz: No such file or directory
(1/32) Purging build-base (0.4-r1)
(2/32) Purging make (4.1-r1)
(3/32) Purging fortify-headers (0.8-r0)
(4/32) Purging g++ (5.3.0-r0)
(5/32) Purging gcc (5.3.0-r0)
(6/32) Purging binutils (2.26-r1)
(7/32) Purging isl (0.14.1-r0)
(8/32) Purging libatomic (5.3.0-r0)
(9/32) Purging pkgconfig (0.25-r1)
(10/32) Purging pkgconf (0.9.12-r0)
(11/32) Purging libc-dev (0.7-r0)
(12/32) Purging musl-dev (1.1.14-r16)
(13/32) Purging git (2.8.6-r0)
(14/32) Purging python (2.7.14-r0)
(15/32) Purging binutils-libs (2.26-r1)
(16/32) Purging mpc1 (1.0.3-r0)
(17/32) Purging mpfr3 (3.1.2-r0)
(18/32) Purging gmp (6.1.0-r0)
(19/32) Purging libgomp (5.3.0-r0)
(20/32) Purging libcurl (7.60.0-r1)
(21/32) Purging ca-certificates (20161130-r0)
Executing ca-certificates-20161130-r0.post-deinstall
(22/32) Purging libssh2 (1.7.0-r0)
(23/32) Purging expat (2.2.0-r1)
(24/32) Purging pcre (8.38-r1)
(25/32) Purging libbz2 (1.0.6-r5)
(26/32) Purging libffi (3.2.1-r2)
(27/32) Purging gdbm (1.11-r1)
(28/32) Purging readline (6.3.008-r4)
(29/32) Purging ncurses-libs (6.0_p20171125-r0)
(30/32) Purging ncurses-terminfo (6.0_p20171125-r0)
(31/32) Purging ncurses-terminfo-base (6.0_p20171125-r0)
(32/32) Purging sqlite-libs (3.13.0-r2)
Executing busybox-1.24.2-r14.trigger
OK: 6 MiB in 13 packages
Removing intermediate container b7e7ba6a1f5e
 ---> 6dd55983c594
Step 7/7 : ENTRYPOINT [ "/usr/local/bin/npm" ]
 ---> Running in bea19b899cca
Removing intermediate container bea19b899cca
 ---> a50811108f02
Successfully built a50811108f02
Successfully tagged meraki-indoor-location:latest
`

**Comment by mcolmant** [comment]
It's just a warning during the image cleaning, you can safely ignore it.
