### ISSUE TITLE
About emitter server

### ISSUE THREAD

**Issue by bennyalva** [IndoorLocation/meraki-indoor-location#17]
what about the emitter server missing or was replaced, thank you

**Comment by mcolmant** [comment]
Hello, they have been merged to ease the deployment.

**Comment by bennyalva** [comment]
understand, so i have the indoorLocation in redis with "the emitter server" this information will be send to mapwize to can see them position on map?

**Comment by mcolmant** [comment]
Once you have the listener and emitter started, you will need to configure your meraki (Network-wide > General >> Location and scanning) to push the notifications to the listener. Please look at the README to align the Meraki floor plans and Mapwize layers.

**Comment by bennyalva** [comment]
in fact the server is running and recieve data from meraky!!
![image](https://user-images.githubusercontent.com/47990324/58196044-fc345880-7c8e-11e9-9343-242964e87b61.png)

then that information is saving in redis!!
![image](https://user-images.githubusercontent.com/47990324/58196161-4ddce300-7c8f-11e9-8d87-05f2eb8eb5ee.png)

finally i am on mapwize and put the require values to can see the positions from data redis but i don't see any location on map
![image](https://user-images.githubusercontent.com/47990324/58196498-0d319980-7c90-11e9-988d-35c4ed7461d1.png)
 can you help me about that !!??
Thank you!!

**Comment by mcolmant** [comment]
Great! That’s a good news to hear. It’s probably linked to the URL used as the indoorLocationSocketUrl. You cannot use your local address (not accessible by Ever y ont). You need to expose your local address with ngrok (https://ngrok.com/) or serveo (http://serveo.net/) and then use the public address.

**Comment by bennyalva** [comment]
i understand, so i have a question about indoor Location because for example if meraki send 300 devices seen near always is the same indoor location for all divices, will be necessary setting something more into meraky dashboard!?

**Comment by mcolmant** [comment]
It depends of the number of you access points. The more, the better.
